#!/bin/bash -e

#
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

HOME=/opt/app-root/src
DEPLOY_DIR=/opt/openshift

# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build artifacts
ARTIFACT_DIR=${ARTIFACT_DIR-target}

function copy_artifacts() {
  if [ -d $LOCAL_SOURCE_DIR/$1 ]; then
    echo "Copying all JAR artifacts from $LOCAL_SOURCE_DIR/$1 directory into $DEPLOY_DIR for later deployment..."
    cp -v $LOCAL_SOURCE_DIR/$1/*.jar $DEPLOY_DIR 2> /dev/null
  fi
}


mvn --version

mvn clean package -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga
ERR=$?
if [ $ERR -ne 0 ]; then
  echo "Aborting due to error code $ERR from Maven build"
  exit $ERR
fi

cd target
unzip component-server.zip
mv component-server-distribution/* $DEPLOY_DIR
mkdir -p $DEPLOY_DIR/.m2/repository/org/talend/demo/1.0.0
cp target/component-runtime-demo-openshift-*.jar $DEPLOY_DIR/.m2/repository/org/talend/demo/1.0.0/demo-1.0.0.jar

cat > $DEPLOY_DIR/bin/setenv.sh << EOF
#! /bin/sh
export MEECROWAVE_OPTS="$MEECROWAVE_OPTS -Dtalend.component.server.maven.repository=$MEECROWAVE_BASE/.m2"
export MEECROWAVE_OPTS="$MEECROWAVE_OPTS -Dtalend.component.server.component.coordinates=org.talend:demo:1.0.0"
export MEECROWAVE_OPTS="$MEECROWAVE_OPTS -Dtalend.component.server.documentation.active=true"
EOF
